name: 'Get branch'
description: 'Get branch to checkout in repository or the default one'
inputs:
  repository:
    description: 'github repository name'
    required: true
  branch:
    description: 'branch name'
    required: true
  default-branch:
    description: 'default branch name'
    required: true
outputs:
  branch:
    description: 'The name of the branch to checkout'
    value: ${{ steps.pick_branch_to_checkout.outputs.branch }}
runs:
  using: 'composite'
  steps:
    - id: pick_branch_to_checkout
      shell: bash
      run: |
        if git ls-remote --exit-code --heads https://github.com/${{ inputs.repository }} ${{ inputs.branch }}; then
          echo ::set-output name=branch::${{ inputs.branch }}
        else
          echo ::set-output name=branch::${{ inputs.default-branch }}
        fi
