FROM node:lts

RUN npm config set registry=http://nexus/repository/npmjs-all/

WORKDIR /ui

# Copy package.json and install dependencies
COPY package*.json ./

RUN npm install

# Copy application source code
COPY . .

EXPOSE 5000

CMD ["npm", "start"]
