apiVersion: skaffold/v1beta11
kind: Config
build:
  insecureRegistries:
    - ${DOCKER_REGISTRY}
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/{{.ORG}}/{{.IMAGE_NAME}}:{{.VERSION}}"
  artifacts:
    - image: nuxeo-web-ui/server
      context: server
      kaniko:
        dockerfile: Dockerfile
        buildArgs:
          DOCKER_REGISTRY: ${DOCKER_REGISTRY}
        buildContext:
          localDir: {}
        flags:
          - --insecure
          - --insecure-pull
          - --insecure-registry=${DOCKER_REGISTRY}
    - image: nuxeo-web-ui/dev
      context: .
      kaniko:
        dockerfile: Dockerfile.dev
        buildArgs:
          DOCKER_REGISTRY: ${DOCKER_REGISTRY}
        buildContext:
          localDir: {}
        flags:
          - --insecure
          - --insecure-pull
          - --insecure-registry=${DOCKER_REGISTRY}
    - image: nuxeo-web-ui
      context: .
      kaniko:
        dockerfile: Dockerfile
        buildArgs:
          DOCKER_REGISTRY: ${DOCKER_REGISTRY}
          SERVER_IMAGE: ${DOCKER_REGISTRY}/${ORG}/nuxeo-web-ui/server:${VERSION}
        buildContext:
          localDir: {}
        flags:
          - --insecure
          - --insecure-pull
          - --insecure-registry=${DOCKER_REGISTRY}
  cluster:
    namespace: webui
