name: "Xvfb recorder"
description: |
  This action sets up an Xvfb server, runs a specified test command, records the Xvfb session using ffmpeg,
  and uploads the recording as an artifact.
  To trigger recording, include the specified tag (by default "[xvfb_record]") in your commit message.
inputs:
  test_command:
    description: |
      The command to run your tests. This command should start the tests and exit when
      they are done. Example: `npm test` or `pytest tests/`
    required: true
  video_extension:
    description: "The video file extension/format to use (e.g. ogv, mp4, mkv)"
    required: false
    default: "mkv"
  timeout_minutes:
    description: "The maximum time (in minutes) to allow the test command to run"
    required: false
    default: 60
  max_attempts:
    description: "The maximum number of attempts to run the test command"
    required: false
    default: 1
  retry_on:
    description: "A comma-separated list of exit codes that should trigger a retry (any, error or timeout)"
    required: false
    default: error
  retry_wait_seconds:
    description: "The number of seconds to wait between retry attempts"
    required: false
    default: 10
  record_video:
    description: "Whether to record video or not (true/false)"
    required: false
    default: true

runs:
  using: "composite"
  steps:
    - name: Xvfb setup & record
      if: inputs.record_video == 'true'
      id: record
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb ffmpeg jwm x11-apps
        echo "Setting up Xvfb on display ${DISPLAY}"
        xvfb-run -n ${DISPLAY#:*} -f "${HOME}/.Xauthority" -s "-screen 0 1200x1080x24" jwm &
        [[ $? -eq 0 ]] && sleep 3 || (echo "Xvfb failed to start"; exit 1)
        ffmpeg -y -nostdin -f x11grab -i ${{ env.DISPLAY }} -s sxga recording.$VIDEXT > ffmpeg.log 2>&1 & FFMPEG="$!"
        echo "FFMPEG=$FFMPEG" >> $GITHUB_OUTPUT
      env:
        DEBIAN_FRONTEND: noninteractive
        DISPLAY: :99
        FFREPORT: file=ffmpeg.log:level=info
        VIDEXT: ${{ inputs.video_extension }}
      working-directory: /tmp

    - name: Run tests using command ${{ inputs.test_command }}
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: ${{ inputs.timeout_minutes }}
        max_attempts: ${{ inputs.max_attempts }}
        retry_on: ${{ inputs.retry_on }}
        retry_wait_seconds: ${{ inputs.retry_wait_seconds }}
        command: ${{ inputs.test_command }}

    - name: Stop recording
      if: always() && steps.record.outcome == 'success'
      shell: bash
      env:
        FFMPEG: ${{ steps.record.outputs.FFMPEG }}
      run: |
        echo "Now killing $(ps --no-headers -C ffmpeg) (registred PID: $FFMPEG)";
        kill $FFMPEG

    - name: Archive Xvfb recording
      if: always() && inputs.record_video == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: xvfbrecording
        path: |
          /tmp/xvfb.${{ inputs.video_extension }}
          /tmp/ffmpeg.log
