#!/usr/bin/env bash
#
# validation-init.sh — set up the evidence tree, capture harness and execution log
# for a bug-fix validation run (Test Engineer 3 workflow).
#
# Everything a validation run produces lives under one per-ticket directory, so a
# run can be archived, attached to Jira or re-read months later without hunting
# through /tmp. The harness gets its own node_modules (puppeteer + the screen
# recorder, which bundles ffmpeg) so nothing is installed into the repo.
#
# Usage:
#   validation-init.sh <TICKET-ID> [options]
#   validation-init.sh WEBUI-1234                  # create (or reuse) the workspace
#   validation-init.sh WEBUI-1234 --print          # re-print the environment
#   validation-init.sh WEBUI-1234 --no-harness     # skip the puppeteer install
#   validation-init.sh WEBUI-1234 --with-firefox   # add the second browser engine (~2 min, ~300 MB)
#   validation-init.sh WEBUI-1234 --force          # recreate from scratch
#   validation-init.sh WEBUI-1234 --remove         # delete the workspace (asks about evidence)
#
# Environment overrides:
#   NX_VAL_ROOT   Evidence root for all tickets (default: ~/Desktop/jira-evidence). The workspace
#                 itself is $NX_VAL_ROOT/<TICKET>/validation, a sibling of the fix/ and reproduce/
#                 folders written by the other two skills. Never write directly to ~/Desktop.
#   NX_VAL_REPO   nuxeo-web-ui checkout to validate (default: this script's repo)

set -euo pipefail

die() { printf 'error: %s\n' "$*" >&2; exit 1; }
note() { printf '  %s\n' "$*"; }
step() { printf '\n==> %s\n' "$*"; }

# ---------------------------------------------------------------- arg parsing

[ $# -ge 1 ] || die "missing <TICKET-ID>. See the header of $0 for usage."

TICKET=$(printf '%s' "$1" | tr '[:lower:]' '[:upper:]')
shift
case "$TICKET" in
  [A-Z]*-[0-9]*) ;;
  *) die "'$TICKET' is not a ticket id (expected e.g. WEBUI-1234 or ELEMENTS-1856)" ;;
esac

ACTION=create
HARNESS=1
FIREFOX=0
FORCE=0
while [ $# -gt 0 ]; do
  case "$1" in
    --print) ACTION=print; shift ;;
    --remove) ACTION=remove; shift ;;
    --no-harness) HARNESS=0; shift ;;
    --with-firefox) FIREFOX=1; shift ;;
    --force) FORCE=1; shift ;;
    -h|--help) sed -n '2,26p' "$0"; exit 0 ;;
    *) die "unknown option '$1'" ;;
  esac
done

# ------------------------------------------------------------------- geometry

script_dir=$(cd "$(dirname "$0")" && pwd)
REPO=${NX_VAL_REPO:-$(git -C "$script_dir" rev-parse --show-toplevel 2>/dev/null || true)}
[ -n "$REPO" ] || die "could not locate the nuxeo-web-ui checkout; set NX_VAL_REPO"

ROOT=${NX_VAL_ROOT:-$HOME/Desktop/jira-evidence}
DIR=$ROOT/$TICKET/validation
EVIDENCE=$DIR/Evidence
HARNESS_DIR=$DIR/harness
LOG=$DIR/run.log
ENVFILE=$DIR/env.sh

print_env() {
  cat <<EOF

Validation workspace: $TICKET
  workspace      $DIR
  evidence       $EVIDENCE
  harness        $HARNESS_DIR
  execution log  $LOG
  repo           $REPO

  source it:     . $ENVFILE
  log an action: nxval_log "started target container on 8100"

Next: bash .cursor/skills/bug-fix-validation/scripts/dual-branch-up.sh $TICKET --target <base> --fixed <branch>
EOF
}

# --------------------------------------------------------------------- remove

if [ "$ACTION" = remove ]; then
  step "Removing the validation workspace for $TICKET"
  [ -d "$DIR" ] || { note "nothing at $DIR"; exit 0; }
  if [ -d "$EVIDENCE" ] && [ "$FORCE" = 0 ]; then
    die "$EVIDENCE still holds evidence; re-run with --force to delete it"
  fi
  rm -rf "$DIR"
  note "removed $DIR"
  exit 0
fi

# ---------------------------------------------------------------------- print

if [ "$ACTION" = print ]; then
  [ -f "$ENVFILE" ] || die "no workspace at $DIR — create it first"
  print_env
  exit 0
fi

# --------------------------------------------------------------------- create

if [ -d "$DIR" ] && [ "$FORCE" = 1 ]; then
  step "Recreating the workspace (--force)"
  rm -rf "$HARNESS_DIR" "$ENVFILE"
fi

step "Creating the evidence tree"
for sub in Before After Videos Logs Console Network Traces Reports Reports/proposed-tests; do
  mkdir -p "$EVIDENCE/$sub"
done
note "$EVIDENCE"

touch "$LOG"

step "Writing $ENVFILE"
cat > "$ENVFILE" <<EOF
# Generated by validation-init.sh — source this in every shell of the $TICKET validation run.
export NX_VAL_TICKET=$TICKET
export NX_VAL_DIR=$DIR
export NX_VAL_EVIDENCE=$EVIDENCE
export NX_VAL_HARNESS=$HARNESS_DIR
export NX_VAL_LOG=$LOG
export NX_VAL_REPO=$REPO

# Append a timestamped line to the execution log. Every command, decision and
# environment detail goes here so the run stays reproducible.
nxval_log() { printf '%s | %s\n' "\$(date -u +%FT%TZ)" "\$*" | tee -a "\$NX_VAL_LOG"; }
EOF
note "exports NX_VAL_* and the nxval_log helper"

# ------------------------------------------------------------------- harness

if [ "$HARNESS" = 1 ]; then
  step "Preparing the capture harness"
  mkdir -p "$HARNESS_DIR"
  [ -f "$HARNESS_DIR/package.json" ] ||
    printf '{\n  "name": "nx-validation-harness",\n  "private": true\n}\n' > "$HARNESS_DIR/package.json"
  cp "$script_dir/nuxeo-capture.js" "$HARNESS_DIR/nuxeo-capture.js"

  if [ -d "$HARNESS_DIR/node_modules/puppeteer" ] && [ -d "$HARNESS_DIR/node_modules/puppeteer-screen-recorder" ]; then
    note "dependencies already installed"
  else
    note "installing puppeteer + puppeteer-screen-recorder (bundles its own ffmpeg)"
    # Retry: the npm registry and the Chrome download are the two flakiest steps of
    # the whole workflow, and a failed harness blocks every capture phase.
    installed=0
    for delay in 0 5 15 45; do
      [ "$delay" = 0 ] || { note "retrying in ${delay}s…"; sleep "$delay"; }
      if (cd "$HARNESS_DIR" && npm install --no-audit --no-fund puppeteer puppeteer-screen-recorder \
            >> "$LOG" 2>&1); then
        installed=1
        break
      fi
    done
    if [ "$installed" = 1 ]; then
      note "installed (log: $LOG)"
    else
      note "WARNING: harness install failed — screenshots via the playwright MCP still work,"
      note "         but videos/HAR need this install. See $LOG."
    fi
  fi

  # The recorder pins its peer to puppeteer 19, which cannot launch Firefox, so the
  # second engine rides on an aliased modern puppeteer installed only when asked.
  if [ "$FIREFOX" = 1 ]; then
    step "Adding the Firefox engine for the cross-browser pass"
    if (cd "$HARNESS_DIR" && npm install --no-audit --no-fund "puppeteer-modern@npm:puppeteer@^25" \
          >> "$LOG" 2>&1); then
      if (cd "$HARNESS_DIR" && ./node_modules/.bin/puppeteer browsers install firefox >> "$LOG" 2>&1); then
        note "firefox ready — use session({ browser: 'firefox', video: false })"
      else
        note "WARNING: the Firefox binary download failed; run the Safari/Firefox pass manually. See $LOG."
      fi
    else
      note "WARNING: could not install the modern puppeteer alias. See $LOG."
    fi
  fi
fi

printf '%s | validation workspace initialised for %s\n' "$(date -u +%FT%TZ)" "$TICKET" >> "$LOG"
print_env
