name: A11y

on:
  pull_request:
    branches:
      - maintenance-3.1.x

  pull_request_target:
    branches:
      - maintenance-3.1.x
      - lts-2025

  workflow_call:
    inputs:
      branch:
        description: 'Branch to build'
        default: maintenance-3.1.x
        type: string
        required: false
    secrets:
      NPM_PACKAGES_TOKEN:
        required: true
      REPOSITORY_MANAGER_USERNAME:
        required: true
      REPOSITORY_MANAGER_PASSWORD:
        required: true

permissions:
  contents: read

env:
  REFERENCE_BRANCH: maintenance-3.1.x
  NPM_REPOSITORY: https://packages.nuxeo.com/repository/npm-public/
  BRANCH_NAME: ${{ github.head_ref || github.event.pull_request.head.ref || inputs.branch }}

jobs:
  a11y:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || (github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]') || github.event_name == 'workflow_call'

    steps:
      - uses: catchpoint/workflow-telemetry-action@v2
        with:
          comment_on_pr: false

      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ env.BRANCH_NAME }}

      - run: git config user.name "nuxeo-webui-jx-bot" && git config user.email "webui@hyland.com"

      - uses: actions/setup-node@v6
        with:
          registry-url: ${{ env.NPM_REPOSITORY }}
          node-version: 22
          scope: '@nuxeo'

      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Install Web UI
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PACKAGES_TOKEN }}
        run: |
          npm cache clean --force
          npm install
          pushd packages/nuxeo-web-ui-ftest
          npm install
          popd
          pushd packages/nuxeo-designer-catalog
          npm install
          popd

      - name: Update settings.xml with server configuration
        run: |
          echo '<settings>
              <servers>
                <server>
                  <id>maven-internal</id>
                  <username>${{ secrets.REPOSITORY_MANAGER_USERNAME }}</username>
                  <password>${{ secrets.REPOSITORY_MANAGER_PASSWORD }}</password>
                </server>
              </servers>
              </settings>' > ~/.m2/settings.xml

      - name: Web UI build
        run: mvn -B -ntp install

      - name: A11y checks
        run: mvn -B -ntp -f plugin/a11y install