name: A11y

on:
  pull_request:
    branches:
      - maintenance-3.0.x
  workflow_call:
    inputs:
      branch:
        description: 'The current branch'
        default: maintenance-3.0.x
        type: string
        required: false
    secrets:
      NPM_PACKAGES_TOKEN:
        description: 'NPM_PACKAGES_TOKEN'
        required: true
      PACKAGES_AUTH_USER:
        description: 'PACKAGES_AUTH_USER'
        required: true
      PACKAGES_AUTH_TOKEN: 
        description: 'PACKAGES_AUTH_TOKEN'
        required: true

env:
  REFERENCE_BRANCH: maintenance-3.0.x
  NPM_REPOSITORY: https://packages.nuxeo.com/repository/npm-public/
  BRANCH_NAME: ${{ github.head_ref || inputs.branch || 'maintenance-3.0.x' }}

jobs:
  a11y:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ env.BRANCH_NAME }}

    - run: git config user.name "nuxeo-web-ui-jx-bot" && git config user.email "ui+jx-bot@nuxeo.com"

    - uses: actions/setup-node@v1
      with:
        registry-url: ${{ env.NPM_REPOSITORY }}
        node-version: '12'
        scope: '@nuxeo'

    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: 'Update settings.xml with server configuration'
      run: |
        echo '<settings>
            <servers>
              <server>
                <id>maven-internal</id>
                <username>${{ secrets.PACKAGES_AUTH_USER }}</username>
                <password>${{ secrets.PACKAGES_AUTH_TOKEN }}</password>
              </server>
            </servers>
            </settings>' > ~/.m2/settings.xml

    - name: Web UI build
      run: mvn -B -ntp install

    - name: A11y checks
      run: mvn -B -ntp -f plugin/a11y install
