# Workflow that syncronizes translations from Crowdin
name: Crowdin Sync

on:
  # Make workflow reusable, to be called by the scheduled crowdin workflow in the default branch
  workflow_call:

  # Sync when a commit is done on the reference branches
  push:
    branches: ["lts-2025"]
    paths:
      - 'i18n/messages.json'

permissions:
  contents: write
  pull-requests: write

jobs:
  # in uses, cannot use environment variable for {owner}/{repo} nor matrix strategy variable for {ref}
  # thus hardcoding them
  call-workflow-in-lts-2025:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    uses: nuxeo/nuxeo-web-ui/.github/workflows/crowdin.yaml@lts-2025
    secrets: inherit
    needs: crowdin

  crowdin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: lts-2025

      - name: Crowdin Action
        id: crowdin-sync
        uses: crowdin/github-action@v2.16.2
        with:
          # Disable 'git checkout "${GITHUB_REF#refs/heads/}"'
          skip_ref_checkout: true
          # Tokens
          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
          # Load external configuration file (to support translation rename)
          config: crowdin-conf.yml

          # Upload sources for translation
          upload_sources: true

          # Auto-approve reference sentences we are pushing (english)
          auto_approve_imported: true

          # Name of the branch where to merge the translations
          localization_branch_name: crowdin-translations-update-lts-2025
          pull_request_base_branch_name: lts-2025
          create_pull_request: true
          pull_request_title: 'New Crowdin translations by GitHub Action (lts-2025)'
          pull_request_body: 'New Crowdin pull request with translations lts 2025'

          # The commit message
          commit_message: 'Automatic update of translations from Crowdin lts 2023'

          # Automatically download all the new translations
          download_translations: true

          # User properties
          github_user_name: nuxeo-webui-jx-bot
          github_user_email: webui@hyland.com

        env:
          GITHUB_TOKEN: ${{ secrets.WEBUI_JX_BOT_GITHUB_ACTIONS_TOKEN }}