name: Dependabot PR Checks

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  lint:
    if: github.actor == 'dependabot[bot]'
    uses: nuxeo/ui-team-gh-actions/.github/workflows/lint.yaml@lts-2025
    with:
      branch: ${{ github.event.pull_request.head.ref }}
    secrets:
      NPM_PACKAGES_TOKEN: ${{ secrets.NPM_PACKAGES_TOKEN }}

  test:
    if: github.actor == 'dependabot[bot]'
    needs: lint
    uses: nuxeo/ui-team-gh-actions/.github/workflows/test.yaml@lts-2025
    with:
      branch: ${{ github.event.pull_request.head.ref }}
    secrets:
      NPM_PACKAGES_TOKEN: ${{ secrets.NPM_PACKAGES_TOKEN }}

  a11y:
    if: github.actor == 'dependabot[bot]'
    needs: test
    uses: nuxeo/ui-team-gh-actions/.github/workflows/a11y.yaml@lts-2025
    with:
      branch: ${{ github.event.pull_request.head.ref }}
    secrets:
      NPM_PACKAGES_TOKEN: ${{ secrets.NPM_PACKAGES_TOKEN }}
      REPOSITORY_MANAGER_USERNAME: ${{ secrets.REPOSITORY_MANAGER_USERNAME }}
      REPOSITORY_MANAGER_PASSWORD: ${{ secrets.REPOSITORY_MANAGER_PASSWORD }}

  ftests:
    if: github.actor == 'dependabot[bot]'
    needs: a11y
    uses: nuxeo/ui-team-gh-actions/.github/workflows/ftest.yaml@lts-2025
    with:
      branch: ${{ github.event.pull_request.head.ref }}
    secrets:
      NPM_PACKAGES_TOKEN: ${{ secrets.NPM_PACKAGES_TOKEN }}
      REPOSITORY_MANAGER_USERNAME: ${{ secrets.REPOSITORY_MANAGER_USERNAME }}
      REPOSITORY_MANAGER_PASSWORD: ${{ secrets.REPOSITORY_MANAGER_PASSWORD }}