name: Dependabot PR Checks

on:
  pull_request:
    branches:
      - maintenance-3.1.x
      - lts-2025
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  lint:
    if: github.actor == 'dependabot[bot]'
    uses: ./.github/workflows/lint.yaml
    with:
      branch: ${{ github.event.pull_request.head.ref }}
    secrets:
      NPM_PACKAGES_TOKEN: ${{ secrets.NPM_PACKAGES_TOKEN }}

  test:
    if: github.actor == 'dependabot[bot]'
    needs: lint
    uses: ./.github/workflows/test.yaml
    with:
      branch: ${{ github.event.pull_request.head.ref }}
    secrets:
      NPM_PACKAGES_TOKEN: ${{ secrets.NPM_PACKAGES_TOKEN }}

  a11y:
    if: github.actor == 'dependabot[bot]'
    needs: test
    uses: ./.github/workflows/a11y.yaml
    with:
      branch: ${{ github.event.pull_request.head.ref }}
    secrets:
      NPM_PACKAGES_TOKEN: ${{ secrets.NPM_PACKAGES_TOKEN }}
      REPOSITORY_MANAGER_USERNAME: ${{ secrets.REPOSITORY_MANAGER_USERNAME }}
      REPOSITORY_MANAGER_PASSWORD: ${{ secrets.REPOSITORY_MANAGER_PASSWORD }}

  ftests:
    if: github.actor == 'dependabot[bot]'
    needs: a11y
    uses: ./.github/workflows/ftest.yaml
    with:
      branch: ${{ github.event.pull_request.head.ref }}
    secrets:
      NPM_PACKAGES_TOKEN: ${{ secrets.NPM_PACKAGES_TOKEN }}
      REPOSITORY_MANAGER_USERNAME: ${{ secrets.REPOSITORY_MANAGER_USERNAME }}
      REPOSITORY_MANAGER_PASSWORD: ${{ secrets.REPOSITORY_MANAGER_PASSWORD }}