name: Functional tests

on:
  push:
    branches:
      - 10.10
  pull_request:
    branches:
      - 10.10

env:
  REFERENCE_BRANCH: '10.10'
  ELEMENTS_REFERENCE_BRANCH: 'maintenance-2.4.x'
  NPM_REPOSITORY: 'https://packages.nuxeo.com/repository/npm-public/'
  HF_VERSION: '56'
  ELEMENTS_BRANCH: ${{ github.head_ref || 'maintenance-2.4.x' }}
  WEBUI_BRANCH: ${{ github.head_ref || '10.10' }}
  PLUGIN_BRANCH: ${{ github.head_ref || '2.4_10.10' }}

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      webui_branch: ${{ steps.pick_nuxeo_web_ui_branch.outputs.branch }}
      elements_branch: ${{ steps.pick_nuxeo_elements_branch.outputs.branch }}
      ui_elements_branch: ${{ steps.pick_nuxeo_ui_elements_branch.outputs.branch }}
      dataviz_elements_branch: ${{ steps.pick_nuxeo_dataviz_elements_branch.outputs.branch }}
      plugin_branch: ${{ steps.pick_plugin_nuxeo_web_ui_branch.outputs.branch }}
      itests_branch: ${{ steps.pick_plugin_nuxeo_web_ui_itests_branch.outputs.branch }}
    steps:
      - name: Build parameters
        run: echo '${{ toJSON(github.event.inputs) }}'

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Determine nuxeo-web-ui branch to use
        id: pick_nuxeo_web_ui_branch
        uses: nuxeo/ui-team-gh-actions/get-branch@ca09d5c52a62e297502d3572c36d813be927982a
        with:
          repository: nuxeo/nuxeo-web-ui
          branch: ${{ env.WEBUI_BRANCH }}
          default-branch: ${{ env.REFERENCE_BRANCH }}

      - name: Determine nuxeo-elements branch to use
        id: pick_nuxeo_elements_branch
        uses: nuxeo/ui-team-gh-actions/get-branch@ca09d5c52a62e297502d3572c36d813be927982a
        with:
          repository: nuxeo/nuxeo-elements
          branch: ${{ env.ELEMENTS_BRANCH }}
          default-branch: ${{ env.ELEMENTS_REFERENCE_BRANCH }}

      - name: Determine nuxeo-ui-elements branch to use
        id: pick_nuxeo_ui_elements_branch
        uses: nuxeo/ui-team-gh-actions/get-branch@ca09d5c52a62e297502d3572c36d813be927982a
        with:
          repository: nuxeo/nuxeo-ui-elements
          branch: ${{ env.ELEMENTS_BRANCH }}
          default-branch: ${{ env.ELEMENTS_REFERENCE_BRANCH }}

      - name: Determine nuxeo-dataviz-elements branch to use
        id: pick_nuxeo_dataviz_elements_branch
        uses: nuxeo/ui-team-gh-actions/get-branch@ca09d5c52a62e297502d3572c36d813be927982a
        with:
          repository: nuxeo/nuxeo-dataviz-elements
          branch: ${{ env.ELEMENTS_BRANCH }}
          default-branch: ${{ env.ELEMENTS_REFERENCE_BRANCH }}

      - name: Determine plugin-nuxeo-web-ui branch to use
        id: pick_plugin_nuxeo_web_ui_branch
        uses: nuxeo/ui-team-gh-actions/get-branch@ca09d5c52a62e297502d3572c36d813be927982a
        with:
          repository: nuxeo/plugin-nuxeo-web-ui
          branch: ${{ env.PLUGIN_BRANCH }}
          default-branch: '2.4_10.10'

      - name: Determine nuxeo-web-ui-itests branch to use
        id: pick_plugin_nuxeo_web_ui_itests_branch
        uses: nuxeo/ui-team-gh-actions/get-branch@ca09d5c52a62e297502d3572c36d813be927982a
        with:
          repository: nuxeo/nuxeo-web-ui-itests
          branch: ${{ env.WEBUI_BRANCH }}
          default-branch: ${{ env.REFERENCE_BRANCH }}

  build-webui:
    name: Build Web UI
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout nuxeo-web-ui repo
        uses: actions/checkout@v2
        with:
          path: nuxeo-web-ui
          ref: ${{ needs.setup.outputs.webui_branch }}

      - uses: actions/setup-node@v2
        with:
          node-version: '10'

      - run: npm install -g bower

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: 'Update settings.xml with server configuration'
        run: |
          echo '<settings>
              <servers>
                <server>
                  <id>maven-internal</id>
                  <username>${{ secrets.PACKAGES_AUTH_USER }}</username>
                  <password>${{ secrets.PACKAGES_AUTH_TOKEN }}</password>
                </server>
              </servers>
              </settings>' > ~/.m2/settings.xml

      - name: Checkout the nuxeo-elements repo
        uses: actions/checkout@v2
        with:
          repository: nuxeo/nuxeo-elements
          path: nuxeo-elements
          fetch-depth: 1
          ref: ${{ needs.setup.outputs.elements_branch }}

      - name: Checkout the nuxeo-ui-elements repo
        uses: actions/checkout@v2
        with:
          repository: nuxeo/nuxeo-ui-elements
          path: nuxeo-ui-elements
          fetch-depth: 1
          ref: ${{ needs.setup.outputs.ui_elements_branch }}

      - name: Checkout the nuxeo-dataviz-elements repo
        uses: actions/checkout@v2
        with:
          repository: nuxeo/nuxeo-dataviz-elements
          path: nuxeo-dataviz-elements
          fetch-depth: 1
          ref: ${{ needs.setup.outputs.dataviz_elements_branch }}

      - name: Install Elements
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PACKAGES_TOKEN }}
        run: |
          pushd nuxeo-elements
          npm install && bower install
          popd
          pushd nuxeo-ui-elements
          npm install && bower install
          rm -rf bower_components/nuxeo-elements
          rsync -av --exclude='node_modules' --exclude='.git' --exclude='bower_components' ../nuxeo-elements bower_components
          popd
          pushd nuxeo-dataviz-elements
          npm install && bower install
          rm -rf bower_components/nuxeo-elements
          rsync -av --exclude='node_modules' --exclude='.git' --exclude='bower_components' ../nuxeo-elements bower_components
          popd

      - name: Install Web UI
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PACKAGES_TOKEN }}
        run: |
          pushd nuxeo-web-ui
          bower install && npm install
          popd

      - name: Lint Web UI
        run: |
          pushd nuxeo-web-ui
          npm run lint
          popd

      - name: Link Nuxeo Elements to Web UI
        run: |
          pushd nuxeo-web-ui
          rm -rf bower_components/nuxeo-elements bower_components/nuxeo-ui-elements bower_components/nuxeo-dataviz-elements
          rsync -av --exclude='node_modules' --exclude='.git' --exclude='bower_components' ../nuxeo-elements bower_components
          rsync -av --exclude='node_modules' --exclude='.git' --exclude='bower_components' ../nuxeo-ui-elements bower_components
          rsync -av --exclude='node_modules' --exclude='.git' --exclude='bower_components' ../nuxeo-dataviz-elements bower_components
          popd

      - name: Nuxeo package build
        run: |
          pushd nuxeo-web-ui
          sed -i 's/10.10-HF[0-9]\{2\}-SNAPSHOT/10.10-HF${{ env.HF_VERSION }}/g' pom.xml
          mvn install -ntp -DskipInstall
          popd

      - uses: actions/upload-artifact@v2
        with:
          name: webui-build
          path: |
            nuxeo-web-ui/pom.xml
            nuxeo-web-ui/target/nuxeo-web-ui-*.jar

  functional-tests:
    name: Web UI functional tests
    needs: [ setup, build-webui ]
    runs-on: [ self-hosted, master ]
    steps:
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: 'Update settings.xml with server configuration'
        run: |
          echo '<settings>
              <servers>
                <server>
                  <id>maven-internal</id>
                  <username>${{ secrets.PACKAGES_AUTH_USER }}</username>
                  <password>${{ secrets.PACKAGES_AUTH_TOKEN }}</password>
                </server>
              </servers>
              </settings>' > ~/.m2/settings.xml

      - uses: actions/download-artifact@v2
        with:
          name: webui-build
          path: nuxeo-web-ui

      - name: Install Web UI package
        run: |
          pushd nuxeo-web-ui
          mvn install:install-file -Dfile=target/$(ls target | grep nuxeo-web-ui-10.10) -DpomFile=pom.xml
          popd

      - name: Checkout nuxeo-web-ui-itests repo
        uses: actions/checkout@v2
        with:
          repository: nuxeo/nuxeo-web-ui-itests
          path: nuxeo-web-ui-itests
          ref: ${{ needs.setup.outputs.itests_branch }}

      - name: Update nuxeo-web-ui-itests SNAPSHOT version with sed
        run: |
          pushd nuxeo-web-ui-itests
          grep -rl '10.10-HF[0-9]\{2\}-SNAPSHOT' . --exclude-dir={.git,node_modules,bower_components} --include=pom.xml | xargs sed -i 's/10.10-HF[0-9]\{2\}-SNAPSHOT/10.10-HF${{ env.HF_VERSION }}/g'
          popd

      - name: Build nuxeo-web-ui-itests package
        run: |
          pushd nuxeo-web-ui-itests
          mvn clean install
          popd

      - name: Checkout plugin-nuxeo-web-ui repo
        uses: actions/checkout@v2
        with:
          repository: nuxeo/plugin-nuxeo-web-ui
          fetch-depth: 1
          ref: ${{ needs.setup.outputs.plugin_branch }}
          path: plugin-nuxeo-web-ui

      - name: Update instance.clid
        run: |
          pushd plugin-nuxeo-web-ui/ftest/web-ui/webdriver
          echo '${{ secrets.FTEST_INSTANCE_CLID }}' > instance.clid
          popd

      - name: Update plugin-nuxeo-web-ui SNAPSHOT version with sed
        run: |
          pushd plugin-nuxeo-web-ui
          grep -rl '10.10-HF[0-9]\{2\}-SNAPSHOT' . --exclude-dir={.git,node_modules,bower_components} --include=pom.xml | xargs sed -i 's/10.10-HF[0-9]\{2\}-SNAPSHOT/10.10-HF${{ env.HF_VERSION }}/g'
          grep -rl '2.4.[0-9]\{2\}-SNAPSHOT' . --exclude-dir={.git,node_modules,bower_components} --include={pom.xml,package.json} | xargs sed -i 's/2.4.[0-9]\{2\}-SNAPSHOT/2.4.${{ env.HF_VERSION }}/g'
          popd

      - name: Run Functional tests
        run: |
          pushd plugin-nuxeo-web-ui
          mvn install -ntp -Pftest -DskipInstall
          popd

      - name: Archive reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: |
            plugin-nuxeo-web-ui/**/target/cucumber-reports/**/*.*
            plugin-nuxeo-web-ui/**/reports/*
            plugin-nuxeo-web-ui/**/failsafe-reports/*
            plugin-nuxeo-web-ui/metrics/target/report/*
            plugin-nuxeo-web-ui/**/target/screenshots/*.png
            plugin-nuxeo-web-ui/**/target/results/*.html

      - name: Archive logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: |
            plugin-nuxeo-web-ui/**/log/*.log
            plugin-nuxeo-web-ui/**/nxserver/config/distribution.properties

      - name: Archive packages
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: |
            # HACK - removed the SNAPSHOT because of sed
            # plugin-nuxeo-web-ui/marketplace/target/nuxeo-web-ui-marketplace-*-SNAPSHOT.zip
            plugin-nuxeo-web-ui/marketplace/target/nuxeo-web-ui-marketplace-*.zip
            plugin-nuxeo-web-ui/marketplace-itests/target/nuxeo-web-ui-marketplace-itests-*.zip
