name: Functional tests

on:
  pull_request:
    branches:
      - maintenance-3.1.x
  workflow_call:
    inputs:
      branch:
        description: 'The current branch'
        default: maintenance-3.1.x
        type: string
        required: false
    secrets:
      NPM_PACKAGES_TOKEN:
        description: 'NPM_PACKAGES_TOKEN'
        required: true
      PACKAGES_AUTH_USER:
        description: 'PACKAGES_AUTH_USER'
        required: true
      PACKAGES_AUTH_TOKEN:
        description: 'PACKAGES_AUTH_TOKEN'
        required: true

env:
  REFERENCE_BRANCH: maintenance-3.1.x
  NPM_REPOSITORY: https://packages.nuxeo.com/repository/npm-public/
  BRANCH_NAME: ${{ github.head_ref || inputs.branch || 'maintenance-3.1.x' }}

jobs:
  promote-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://packages.nuxeo.com/repository/npm-public/'
          scope: '@nuxeo'

      - uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH_NAME }}

      - run: git config user.name "nuxeo-webui-jx-bot" && git config user.email "webui@hyland.com"

      - run: echo "VERSION='3.1.18'" >> $GITHUB_ENV

      - name: Update Nuxeo Web UI version to ${{ env.VERSION }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          OLD_VERSION=$(npx -c 'echo "$npm_package_version"')
          # npm version $VERSION --no-git-tag-version
          # pushd packages/nuxeo-web-ui-ftest/
          # npm version $VERSION --no-git-tag-version
          # popd

          find . -type f -not -path "./node_modules/*" -regex ".*\.\(yaml\|sample\|xml\)" -exec sed -i 's/'"$OLD_VERSION"'/'"$VERSION"'/g' {} \;
          # XXX: undo the padded lock (see WEBUI-140)
          sed -i -e 's/<webui.package.version>.*<\/webui.package.version>/<webui.package.version>${project.version}<\/webui.package.version>/g' plugin/web-ui/marketplace/pom.xml

          # # align on same promoted version of elements
          # npm i @nuxeo/nuxeo-elements@$VERSION --save-exact
          # npm i @nuxeo/nuxeo-dataviz-elements@$VERSION --save-exact
          # npm i @nuxeo/nuxeo-ui-elements@$VERSION --save-exact
          # npm i @nuxeo/testing-helpers@$VERSION --save-exact

          echo "--------------------------------------------------------------"
          cat pom.xml
