name: Functional tests

on:
  pull_request:
    branches:
      - maintenance-3.1.x

  pull_request_target:
    branches:
      - maintenance-3.1.x
      - lts-2025

  workflow_call:
    inputs:
      branch:
        description: 'Branch to build'
        default: maintenance-3.1.x
        type: string
        required: false
    secrets:
      NPM_PACKAGES_TOKEN:
        required: true
      REPOSITORY_MANAGER_USERNAME:
        required: true
      REPOSITORY_MANAGER_PASSWORD:
        required: true

permissions:
  contents: read

env:
  REFERENCE_BRANCH: maintenance-3.1.x
  NPM_REPOSITORY: https://packages.nuxeo.com/repository/npm-public/
  BRANCH_NAME: ${{ github.head_ref || inputs.branch || github.event.pull_request.head.ref || 'maintenance-3.1.x' }}
  NODE_OPTIONS: "--max-old-space-size=2048"

jobs:
  ftests:
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_call' || (github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]')
    runs-on:
      group: medium-4cpu-runners

    steps:
      - name: Debug
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Actor: ${{ github.actor }}"
          echo "Condition result: ${{ github.event_name != 'pull_request_target' || github.actor == 'dependabot[bot]' }}"

      - uses: catchpoint/workflow-telemetry-action@v2
        with:
          comment_on_pr: false

      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ env.BRANCH_NAME }}

      - uses: actions/setup-node@v6
        with:
          registry-url: ${{ env.NPM_REPOSITORY }}
          always-auth: true
          scope: '@nuxeo'
          node-version: 22

      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Install dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick poppler-utils libreoffice ffmpeg libwpd-tools ghostscript exiftool
          sudo sed -i '/disable ghostscript format types/,+6d' /etc/ImageMagick-6/policy.xml
          npm install -g bower
          npm install -g gulp-cli

      - name: Determine nuxeo-elements branch to link
        id: pick_nuxeo_elements_branch
        run: |
          if git ls-remote --exit-code --heads https://github.com/nuxeo/nuxeo-elements ${{ env.BRANCH_NAME }}; then
            echo "branch=${{ env.BRANCH_NAME }}" >> $GITHUB_OUTPUT
          else
            echo "branch=${{ env.REFERENCE_BRANCH }}" >> $GITHUB_OUTPUT
          fi

      - name: Install Web UI
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PACKAGES_TOKEN }}
        run: |
          npm cache clean --force
          npm install
          pushd packages/nuxeo-web-ui-ftest
          npm install
          popd
          pushd packages/nuxeo-designer-catalog
          npm install
          popd

      - name: Checkout the nuxeo-elements repo
        uses: actions/checkout@v6
        with:
          repository: nuxeo/nuxeo-elements
          path: nuxeo-elements
          fetch-depth: 1
          ref: ${{ steps.pick_nuxeo_elements_branch.outputs.branch }}

      - name: Pack Elements modules
        run: |
          pushd nuxeo-elements
          for d in core ui dataviz testing-helpers; do
            pushd $d
            echo "ELEMENTS_$(echo $d | tr 'a-z-' 'A-Z_')=$(npm pack 2>&1 | tail -1)" >> $GITHUB_ENV
            popd
          done
          popd

      - name: Link elements to Web UI
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PACKAGES_TOKEN }}
        run: |
          npm install --no-package-lock --@nuxeo:registry="${{ env.NPM_REPOSITORY }}" nuxeo-elements/core/${ELEMENTS_CORE}
          npm install --no-package-lock --@nuxeo:registry="${{ env.NPM_REPOSITORY }}" nuxeo-elements/ui/${ELEMENTS_UI}
          npm install --no-package-lock --@nuxeo:registry="${{ env.NPM_REPOSITORY }}" nuxeo-elements/dataviz/${ELEMENTS_DATAVIZ}
          npm install --no-package-lock --@nuxeo:registry="${{ env.NPM_REPOSITORY }}" nuxeo-elements/testing-helpers/${ELEMENTS_TESTING_HELPERS}

      - name: Update settings.xml with server configuration
        run: |
          echo '<settings>
              <servers>
                <server>
                  <id>maven-internal</id>
                  <username>${{ secrets.REPOSITORY_MANAGER_USERNAME }}</username>
                  <password>${{ secrets.REPOSITORY_MANAGER_PASSWORD }}</password>
                </server>
              </servers>
              </settings>' > ~/.m2/settings.xml

      - name: Functional tests
        env:
          RUN_ALL: false
          BAIL: 0
          HEADLESS: ${{ contains(github.event.pull_request.labels.*.name, 'video') && 'false' || 'true' }}
        uses: Alfresco/alfresco-build-tools/.github/actions/xvfb-record@v11.0.0
        with:
          test_command: mvn -ntp install -Pftest -DskipInstall
          timeout_minutes: 120
          video_name: ${{ contains(github.event.pull_request.labels.*.name, 'video') && 'ftest-video' || '' }}
          max_attempts: 3

      - name: Archive cucumber reports
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: cucumber-reports
          path: ftest/target/cucumber-reports/

      - name: Archive screenshots
        if: failure()
        uses: actions/upload-artifact@v6
        with:
          name: screenshots
          path: ftest/target/screenshots/

      - name: Archive logs
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: logs
          path: |
            **/log/*.log
            **/nxserver/config/distribution.properties

      - name: Archive packages-ftest
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: packages-ftest
          path: |
            plugin/web-ui/marketplace/target/nuxeo-web-ui-marketplace-*.zip
            plugin/itests/marketplace/target/nuxeo-web-ui-marketplace-itests-*.zip