name: Lint

on:
  pull_request:
    branches:
      - lts-2025

  workflow_call:
    inputs:
      branch:
        description: 'Branch to lint'
        type: string
        required: false
    secrets:
      NPM_PACKAGES_TOKEN:
        required: true

permissions:
  contents: read

env:
  BRANCH_NAME: ${{ github.head_ref || inputs.branch || 'lts-2025' }}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ env.BRANCH_NAME }}

      - uses: actions/setup-node@v6
        with:
          registry-url: 'https://packages.nuxeo.com/repository/npm-public/'
          node-version: 22
          scope: '@nuxeo'

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('package-lock.json', 'packages/nuxeo-web-ui-ftest/package-lock.json', 'packages/nuxeo-designer-catalog/package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-

      - name: Install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PACKAGES_TOKEN }}
        run: npm install

      - name: Update @nuxeo packages to latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PACKAGES_TOKEN }}
        run: |
          npm update @nuxeo/nuxeo-elements @nuxeo/nuxeo-ui-elements @nuxeo/nuxeo-dataviz-elements @nuxeo/testing-helpers

      - name: Lint
        run: npm run lint