name: Main

on:
  push:
    branches:
      - lts-2025
  workflow_dispatch:

permissions:
  contents: write

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml
    secrets:
      NPM_PACKAGES_TOKEN: ${{ secrets.NPM_PACKAGES_TOKEN }}

  test:
    uses: ./.github/workflows/test.yaml
    secrets:
      NPM_PACKAGES_TOKEN: ${{ secrets.NPM_PACKAGES_TOKEN }}
      SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
    with:
      branch: lts-2025

  a11y:
    uses: ./.github/workflows/a11y.yaml
    secrets:
      NPM_PACKAGES_TOKEN: ${{ secrets.NPM_PACKAGES_TOKEN }}
      REPOSITORY_MANAGER_USERNAME: ${{ secrets.REPOSITORY_MANAGER_USERNAME }}
      REPOSITORY_MANAGER_PASSWORD: ${{ secrets.REPOSITORY_MANAGER_PASSWORD }}
    with:
      branch: lts-2025

  sonar:
    uses: ./.github/workflows/sonar.yaml
    secrets:
      NPM_PACKAGES_TOKEN: ${{ secrets.NPM_PACKAGES_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    with:
      branch: lts-2025

  ftest:
    uses: ./.github/workflows/ftest.yaml
    secrets:
      NPM_PACKAGES_TOKEN: ${{ secrets.NPM_PACKAGES_TOKEN }}
      REPOSITORY_MANAGER_USERNAME: ${{ secrets.REPOSITORY_MANAGER_USERNAME }}
      REPOSITORY_MANAGER_PASSWORD: ${{ secrets.REPOSITORY_MANAGER_PASSWORD }}
    with:
      branch: lts-2025

  build:
    needs: [lint, test, a11y, ftest, sonar]
    runs-on:
      group: medium-4cpu-runners

    steps:
      - uses: catchpoint/workflow-telemetry-action@v2
        with:
          comment_on_pr: false

      - uses: actions/checkout@v6

      - run: git config user.name "nuxeo-webui-jx-bot" && git config user.email "webui@hyland.com"

      - uses: actions/setup-node@v6
        with:
          registry-url: 'https://packages.nuxeo.com/repository/npm-public/'
          scope: '@nuxeo'

      - name: Cache npm dependencies
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('package.json', 'packages/nuxeo-web-ui-ftest/package.json', 'packages/nuxeo-designer-catalog/package.json') }}
          restore-keys: |
            npm-${{ runner.os }}-

      - name: Setup Maven build
        uses: nuxeo/gh-build-tools/.github/actions/setup-maven-build@v0.10.4
        with:
          java-version: '21'

      - name: Purge cached Nuxeo artifacts
        run: rm -rf ~/.m2/repository/org/nuxeo

      - name: Prepare environment
        run: |
          echo "PACKAGE_VERSION=$(npx -c 'echo "$npm_package_version"')" >> $GITHUB_ENV

      - name: Get prerelease version
        run: |
          git fetch origin --tags
          RC_VERSION=$(git tag --sort=taggerdate --list "v${PACKAGE_VERSION/-SNAPSHOT}*" | tail -1 | tr -d '\n')
          echo "VERSION=$(npx semver -i prerelease --preid rc ${RC_VERSION:-$PACKAGE_VERSION}  | tr -d '\n')" >> $GITHUB_ENV

      - name: Update versions
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PACKAGES_TOKEN }}
        run: |
          find . -type f -not -path "./node_modules/*" -regex ".*\.\(yaml\|sample\|xml\)" -exec sed -i 's/'"$PACKAGE_VERSION"'/'"$VERSION"'/g' {} \;

          # set padded version to build package for connect preprod
          PADDED=$(printf '%03d' $(echo $VERSION | sed -r s/[0-9]+\.[0-9]+\.[0-9]+-rc\.\([0-9]+\)/\\1/g))
          PADDED_VERSION=$(echo $VERSION | sed -E "s/([0-9]+\.[0-9]+\.[0-9]+-rc\.)[0-9]+/\\1$PADDED/g")
          echo "PADDED_VERSION=$PADDED_VERSION" >> $GITHUB_ENV
          sed -i -e 's/\${project.version}/'"$PADDED_VERSION"'/g' plugin/web-ui/marketplace/pom.xml

          npm version ${VERSION} --no-git-tag-version

          # Get latest UI Elements version
          ELEMENTS_VERSION=$(npm view @nuxeo/nuxeo-ui-elements versions --json | jq -r '.[]' | grep -E "2025\.[0-9]+\.[0-9]+-rc\.[0-9]+$" | sort -V | tail -n1)

          echo "Latest nuxeo-elements version: $ELEMENTS_VERSION"

          # Update package.json dependencies and devDependencies
          jq --arg ver "~$ELEMENTS_VERSION" '
            .dependencies."@nuxeo/nuxeo-dataviz-elements" = $ver |
            .dependencies."@nuxeo/nuxeo-elements" = $ver |
            .dependencies."@nuxeo/nuxeo-ui-elements" = $ver |
            .devDependencies."@nuxeo/testing-helpers" = $ver
          ' package.json > tmp.json && mv tmp.json package.json
          echo "Updated all Nuxeo dependencies to version $ELEMENTS_VERSION"

          pushd packages/nuxeo-web-ui-ftest
          npm version ${VERSION} --no-git-tag-version
          popd

      - name: Install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PACKAGES_TOKEN }}
        run: |
          npm ci
          (cd packages/nuxeo-web-ui-ftest && npm ci)
          (cd packages/nuxeo-designer-catalog && npm ci)

      - name: Build packages
        env:
          MVN_REPO_USERNAME: ${{ secrets.REPOSITORY_MANAGER_USERNAME }}
          MVN_REPO_PASSWORD: ${{ secrets.REPOSITORY_MANAGER_PASSWORD }}
        run: |
          mvn -ntp install -DskipInstall
          mvn -B -nsu -ntp -f plugin/itests/addon install
          mvn -B -nsu -ntp -f plugin/itests/marketplace install

      - name: Archive packages
        uses: actions/upload-artifact@v7
        with:
          name: packages
          path: |
            plugin/web-ui/marketplace/target/nuxeo-web-ui-marketplace-*.zip
            plugin/itests/marketplace/target/nuxeo-web-ui-marketplace-itests-*.zip

      - name: Tag
        run: |
          git add package-lock.json packages/nuxeo-web-ui-ftest/package-lock.json
          git commit -a -m "Release ${VERSION}"
          git tag -a v${VERSION} -m "Release ${VERSION}"
          git push origin v${VERSION}

      - name: Publish Nuxeo packages
        env:
          CONNECT_PREPROD_URL: https://nos-preprod-connect.nuxeocloud.com/nuxeo
        run: |
          PACKAGE="plugin/web-ui/marketplace/target/nuxeo-web-ui-marketplace-${PADDED_VERSION}.zip"
          curl -fS -u "${{ secrets.CONNECT_PREPROD_AUTH }}" \
               -F package=@$PACKAGE \
               "$CONNECT_PREPROD_URL/site/marketplace/upload?batch=true"

      - name: Publish Web UI FTest framework
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PACKAGES_TOKEN }}
        run: |
          cd packages/nuxeo-web-ui-ftest
          npm publish --@nuxeo:registry=https://packages.nuxeo.com/repository/npm-public/ --tag SNAPSHOT