name: Ondemand build

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'The name of the branch to build.'
        default: '10.10'
        required: true
      hf_version:
        description: 'HF Version to replace in pom file (HACK)'
        default: '56'
        required: false
      sauce_labs:
        description: 'Run unit tests on Sauce Labs?'
        default: true
        type: boolean
        required: false
      skip_ftests:
        description: 'Skip functional tests?'
        type: boolean
        required: false
      skip_unit_tests:
        description: 'Skip unit tests?'
        type: boolean
        required: false
      generate_metrics:
        description: 'Generate metrics report?'
        type: boolean
        required: false

env:
  REFERENCE_BRANCH: '10.10'
  ELEMENTS_REFERENCE_BRANCH: 'maintenance-2.4.x'
  NPM_REPOSITORY: https://packages.nuxeo.com/repository/npm-public/

jobs:
  build:
    name: Packages
    runs-on: [ self-hosted, master ]
    steps:
    - name: Build parameters
      run: echo "${{ toJSON(github.event.inputs) }}"

    - uses: actions/setup-node@v1
      with:
        registry-url: ${{ env.NPM_REPOSITORY }}
        scope: '@nuxeo'

    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'

    - name: 'Update settings.xml with server configuration'
      run: |
        echo '<settings>
            <servers>
              <server>
                <id>maven-internal</id>
                <username>${{ secrets.PACKAGES_AUTH_USER }}</username>
                <password>${{ secrets.PACKAGES_AUTH_TOKEN }}</password>
              </server>
            </servers>
            </settings>' > ~/.m2/settings.xml

    - name: Check out repository
      uses: actions/checkout@v2

    - name: Determine nuxeo-web-ui branch to use
      id: pick_nuxeo_web_ui_branch
      uses: ./.github/actions/get-branch
      with:
        repository: nuxeo/nuxeo-web-ui
        branch: ${{ github.event.inputs.branch_name }}
        default-branch: ${{ env.REFERENCE_BRANCH }}

    - name: Determine nuxeo-elements branch to use
      id: pick_nuxeo_elements_branch
      uses: ./.github/actions/get-branch
      with:
        repository: nuxeo/nuxeo-elements
        branch: ${{ github.event.inputs.branch_name }}
        default-branch: ${{ env.ELEMENTS_REFERENCE_BRANCH }}

    - name: Determine nuxeo-ui-elements branch to use
      id: pick_nuxeo_ui_elements_branch
      uses: ./.github/actions/get-branch
      with:
        repository: nuxeo/nuxeo-ui-elements
        branch: ${{ github.event.inputs.branch_name }}
        default-branch: ${{ env.ELEMENTS_REFERENCE_BRANCH }}

    - name: Determine plugin-nuxeo-web-ui branch to use
      id: pick_plugin_nuxeo_web_ui_branch
      uses: ./.github/actions/get-branch
      with:
        repository: nuxeo/plugin-nuxeo-web-ui
        branch: ${{ github.event.inputs.branch_name }}
        default-branch: '2.4_10.10'

    - name: Determine nuxeo-web-ui-itests branch to use
      id: pick_plugin_nuxeo_web_ui_itests_branch
      uses: ./.github/actions/get-branch
      with:
        repository: nuxeo/nuxeo-web-ui-itests
        branch: ${{ github.event.inputs.branch_name }}
        default-branch: ${{ env.REFERENCE_BRANCH }}

    - name: Checkout the nuxeo-elements repo
      uses: actions/checkout@v2
      with:
        repository: nuxeo/nuxeo-elements
        path: nuxeo-elements
        fetch-depth: 1
        ref: ${{ steps.pick_nuxeo_elements_branch.outputs.branch }}

    - name: Checkout the nuxeo-ui-elements repo
      uses: actions/checkout@v2
      with:
        repository: nuxeo/nuxeo-ui-elements
        path: nuxeo-ui-elements
        fetch-depth: 1
        ref: ${{ steps.pick_nuxeo_ui_elements_branch.outputs.branch }}

    - name: Install Elements
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_PACKAGES_TOKEN }}
      run: |
        pushd nuxeo-elements
        npm install && bower install
        popd

        pushd nuxeo-ui-elements
        npm install && bower install
        rm -rf bower_components/nuxeo-elements
        rsync -av --exclude='node_modules' --exclude='.git' --exclude='bower_components' ../nuxeo-elements bower_components
        popd

    - name: Lint Elements
      run: |
        pushd nuxeo-elements
        npm run lint
        popd
        pushd nuxeo-ui-elements
        npm run lint
        popd    

    - name: Elements Unit tests
      if: ${{ github.event.inputs.skip_unit_tests == 'false' && github.event.inputs.sauce_labs == 'false' }}
      run: |
        pushd nuxeo-elements
        npm run test
        popd
        pushd nuxeo-ui-elements
        npm run test
        popd

    - name: Elements Unit tests (Sauce Labs)
      if: ${{ github.event.inputs.skip_unit_tests == 'false' && github.event.inputs.sauce_labs == 'true' }}
      env:
        SAUCE_USERNAME: nuxeo-elements
        SAUCE_ACCESS_KEY: ${{ secrets.ELEMENTS_SAUCE_ACCESS_KEY }}
      run: |
        pushd nuxeo-elements
        ./node_modules/.bin/polymer test -l chrome --plugin sauce --job-name nuxeo-elements-pipeline-${{ steps.pick_nuxeo_elements_branch.outputs.branch }} --build-number ${{ github.run_number }}
        popd

    - name: UI Elements Unit tests (Sauce Labs)
      if: ${{ github.event.inputs.skip_unit_tests == 'false' && github.event.inputs.sauce_labs == 'true' }}
      env:
        SAUCE_USERNAME: nuxeo-ui-elements
        SAUCE_ACCESS_KEY: ${{ secrets.UI_ELEMENTS_SAUCE_ACCESS_KEY }}
      run: |
        pushd nuxeo-ui-elements
        ./node_modules/.bin/polymer test -l chrome --plugin sauce --job-name nuxeo-ui-elements-pipeline-${{ steps.pick_nuxeo_ui_elements_branch.outputs.branch }} --build-number ${{ github.run_number }}
        popd

    - name: Checkout nuxeo-web-ui repo
      uses: actions/checkout@v2
      with:
        path: nuxeo-web-ui
        ref: ${{ steps.pick_nuxeo_web_ui_branch.outputs.branch }}

    - name: Install Web UI
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_PACKAGES_TOKEN }}
      run: |
        pushd nuxeo-web-ui
        bower install && npm install
        popd

    - name: Lint Web UI
      run: |
        pushd nuxeo-web-ui
        npm run lint
        popd

    - name: Link elements to Web UI
      run: |
        pushd nuxeo-web-ui
        rm -rf bower_components/nuxeo-elements bower_components/nuxeo-ui-elements
        rsync -av --exclude='node_modules' --exclude='.git' --exclude='bower_components' ../nuxeo-elements bower_components
        rsync -av --exclude='node_modules' --exclude='.git' --exclude='bower_components' ../nuxeo-ui-elements bower_components
        popd

    # HACK - this is a workaround that will be removed. Necessary because SNAPSHOT version might not be published yet
    - name: Update nuxeo-web-ui SNAPSHOT version with sed
      run: |
        pushd nuxeo-web-ui
        sed -i 's/10.10-HF[0-9]\{2\}-SNAPSHOT/10.10-HF${{ github.event.inputs.hf_version }}/g' pom.xml
        popd

    - name: Nuxeo package build
      run: |
        pushd nuxeo-web-ui
        mvn install -DskipInstall
        popd

    - name: Checkout nuxeo-web-ui-itests repo
      uses: actions/checkout@v2
      with:
        repository: nuxeo/nuxeo-web-ui-itests
        path: nuxeo-web-ui-itests
        ref:  ${{ steps.pick_plugin_nuxeo_web_ui_itests_branch.outputs.branch }}

    # HACK - this is a workaround that will be removed. Necessary because SNAPSHOT version might not be published yet
    - name: Update nuxeo-web-ui-itests SNAPSHOT version with sed
      run: |
        pushd nuxeo-web-ui-itests
        grep -rl '10.10-HF[0-9]\{2\}-SNAPSHOT' . --exclude-dir={.git,node_modules,bower_components} | xargs sed -i 's/10.10-HF[0-9]\{2\}-SNAPSHOT/10.10-HF${{ github.event.inputs.hf_version }}/g'
        popd

    - name: Build nuxeo-web-ui-itests package
      run: |
        pushd nuxeo-web-ui-itests
        mvn clean install
        popd

    - name: Checkout plugin-nuxeo-web-ui repo
      uses: actions/checkout@v2
      with:
        repository: nuxeo/plugin-nuxeo-web-ui
        fetch-depth: 1
        ref: ${{ steps.pick_plugin_nuxeo_web_ui_branch.outputs.branch }}
        path: plugin-nuxeo-web-ui

    # HACK - this is a workaround that will be removed. Necessary because SNAPSHOT version might not be published yet
    - name: Update plugin-nuxeo-web-ui SNAPSHOT version with sed
      run: |
        pushd plugin-nuxeo-web-ui
        grep -rl '10.10-HF[0-9]\{2\}-SNAPSHOT' . --exclude-dir={.git,node_modules,bower_components} | xargs sed -i 's/10.10-HF[0-9]\{2\}-SNAPSHOT/10.10-HF${{ github.event.inputs.hf_version }}/g'
        grep -rl '2.4.[0-9]\{2\}-SNAPSHOT' . --exclude-dir={.git,node_modules,bower_components} | xargs sed -i 's/2.4.[0-9]\{2\}-SNAPSHOT/2.4.${{ github.event.inputs.hf_version }}/g'
        popd

    - name: Run Functional tests
      run: |
        profiles=()
        if [ ${{ github.event.inputs.skip_ftests }} = "false" ]
        then 
          profiles+=('ftest') 
        fi
        if ${{ github.event.inputs.generate_metrics }}
        then 
          profiles+=('metrics') 
        fi
        active_profiles=""
        if [ ${#profiles[@]} -gt 0 ] 
        then
          active_profiles="-P$(printf -v active_profiles '%s,' "${profiles[@]}" && echo "${active_profiles%,}")"
        fi
        pushd plugin-nuxeo-web-ui
        mvn install $active_profiles -DskipInstall
        popd

    - name: Archive reports
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: reports
        path: |
          plugin-nuxeo-web-ui/**/target/cucumber-reports/*.json
          plugin-nuxeo-web-ui/**/reports/*
          plugin-nuxeo-web-ui/**/failsafe-reports/*
          plugin-nuxeo-web-ui/metrics/target/report/*
          plugin-nuxeo-web-ui/**/target/screenshots/*.png
          plugin-nuxeo-web-ui/**/target/results/*.html

    - name: Archive logs
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: |
          plugin-nuxeo-web-ui/**/log/*.log
          plugin-nuxeo-web-ui/**/nxserver/config/distribution.properties

    - name: Archive packages
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: packages
        path: |
          # HACK - removed the SNAPSHOT because of sed
          # plugin-nuxeo-web-ui/marketplace/target/nuxeo-web-ui-marketplace-*-SNAPSHOT.zip
          plugin-nuxeo-web-ui/marketplace/target/nuxeo-web-ui-marketplace-*.zip
          plugin-nuxeo-web-ui/marketplace-itests/target/nuxeo-web-ui-marketplace-itests-*.zip
