name: Ondemand build

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'The name of the branch to build.'
        default: 'maintenance-3.0.x'
        required: true
      sauce_labs:
        description: 'Run unit tests on Sauce Labs?'
        default: true
        type: boolean
        required: false
      skip_ftests:
        description: 'Skip functional tests?'
        type: boolean
        required: false
      skip_unit_tests:
        description: 'Skip unit tests?'
        type: boolean
        required: false
      generate_metrics:
        description: 'Generate metrics report?'
        type: boolean
        required: false
      run_all:
        description: 'Skip fail fast premise?'
        type: boolean
        required: false
      bail:
        description: 'Number of failed features to stop test runner (0 means not applicable).'
        default: 0
        required: false

env:
  REFERENCE_BRANCH: maintenance-3.0.x
  NPM_REPOSITORY: https://packages.nuxeo.com/repository/npm-public/

jobs:
  build:
    name: Build
    runs-on: [ self-hosted, master ]
    steps:
      - uses: actions/setup-node@v1
        with:
          registry-url: ${{ env.NPM_REPOSITORY }}
          scope: '@nuxeo'

      - name: Determine nuxeo-web-ui branch to use
        id: pick_nuxeo_web_ui_branch
        run: |
          if git ls-remote --exit-code --heads https://github.com/nuxeo/nuxeo-web-ui ${{ github.event.inputs.branch_name }}; then
            echo ::set-output name=branch::${{ github.event.inputs.branch_name }}
          else
            echo ::set-output name=branch::${{ env.REFERENCE_BRANCH }}
          fi

      - name: Determine nuxeo-elements branch to use
        id: pick_nuxeo_elements_branch
        run: |
          if git ls-remote --exit-code --heads https://github.com/nuxeo/nuxeo-elements ${{ github.event.inputs.branch_name }}; then
            echo ::set-output name=branch::${{ github.event.inputs.branch_name }}
          else
            echo ::set-output name=branch::${{ env.REFERENCE_BRANCH }}
          fi

      - name: Checkout nuxeo-web-ui repo
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.pick_nuxeo_web_ui_branch.outputs.branch }}

      - name: Install Web UI
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PACKAGES_TOKEN }}
        run: |
          npm install
          pushd packages/nuxeo-web-ui-ftest
          npm install
          popd

      - name: Lint Web UI
        run: npm run lint

      - name: Checkout the nuxeo-elements repo
        uses: actions/checkout@v2
        with:
          repository: nuxeo/nuxeo-elements
          path: nuxeo-elements
          fetch-depth: 1
          ref: ${{ steps.pick_nuxeo_elements_branch.outputs.branch }}

      - name: Install Elements
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PACKAGES_TOKEN }}
        run: |
          pushd nuxeo-elements
          npm install
          npm run bootstrap
          popd
      
      - name: Lint Elements
        run: |
          pushd nuxeo-elements
          npm run lint
          popd

      - name: Elements Unit tests
        if: ${{ github.event.inputs.skip_unit_tests == 'false' && github.event.inputs.sauce_labs == 'false' }}
        run: |
          pushd nuxeo-elements
          npm run test
          popd

      - name: Elements Unit tests (Sauce Labs)
        if: ${{ github.event.inputs.skip_unit_tests == 'false' && github.event.inputs.sauce_labs == 'true' }}
        env:
          SAUCE_USERNAME: nuxeo-web-ui
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        run: |
          pushd nuxeo-elements
          npm run test
          popd
      
      - name: Pack Elements modules
        run: |
          pushd nuxeo-elements
          pushd core
          echo "ELEMENTS_CORE=$(npm pack 2>&1 | tail -1)" >> $GITHUB_ENV
          popd

          pushd ui
          echo "ELEMENTS_UI=$(npm pack 2>&1 | tail -1)" >> $GITHUB_ENV
          popd

          pushd dataviz
          echo "ELEMENTS_DATAVIZ=$(npm pack 2>&1 | tail -1)" >> $GITHUB_ENV
          popd
          popd

      - name: Link elements to Web UI
        run: |
          npm install --no-package-lock --@nuxeo:registry="${{ env.NPM_REPOSITORY }}" nuxeo-elements/core/${ELEMENTS_CORE}
          npm install --no-package-lock --@nuxeo:registry="${{ env.NPM_REPOSITORY }}" nuxeo-elements/ui/${ELEMENTS_UI}
          npm install --no-package-lock --@nuxeo:registry="${{ env.NPM_REPOSITORY }}" nuxeo-elements/dataviz/${ELEMENTS_DATAVIZ}

      - name: Web UI Unit tests
        if: ${{ github.event.inputs.skip_unit_tests == 'false' && github.event.inputs.sauce_labs == 'false' }}
        run: npm run test

      - name: Web UI Unit tests (Sauce Labs)
        if: ${{ github.event.inputs.skip_unit_tests == 'false' && github.event.inputs.sauce_labs == 'true' }}
        env:
          SAUCE_USERNAME: nuxeo-web-ui
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        run: npm run test

      - name: 'Update settings.xml with server configuration'
        run: |
          echo '<settings>
              <servers>
                <server>
                  <id>maven-internal</id>
                  <username>${{ secrets.PACKAGES_AUTH_USER }}</username>
                  <password>${{ secrets.PACKAGES_AUTH_TOKEN }}</password>
                </server>
              </servers>
              </settings>' > ~/.m2/settings.xml

      - name: Nuxeo package build and Ftests
        env:
          RUN_ALL: ${{ github.event.inputs.run_all }}
          BAIL: ${{ github.event.inputs.bail }}
        run: | 
          profiles=()
          if [ ${{ github.event.inputs.skip_ftests }} = "false" ]
          then 
            profiles+=('ftest') 
          fi
          if ${{ github.event.inputs.generate_metrics }}
          then 
            profiles+=('metrics') 
          fi
          active_profiles=""
          if [ ${#profiles[@]} -gt 0 ] 
          then
            active_profiles="-P$(printf -v active_profiles '%s,' "${profiles[@]}" && echo "${active_profiles%,}")"
          fi
          mvn install $active_profiles -DskipInstall

      - name: Archive cucumber reports
        uses: actions/upload-artifact@v2
        with:
          name: cucumber-reports
          path: |
            ftest/target/cucumber-reports/

      - name: Archive logs
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: |
            **/log/*.log
            **/nxserver/config/distribution.properties

      - name: Archive packages
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: |
            plugin/web-ui/marketplace/target/nuxeo-web-ui-marketplace-*.zip
            plugin/itests/marketplace/target/nuxeo-web-ui-marketplace-itests-*.zip
