name: Preview

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches:
      - maintenance-3.1.x

  workflow_dispatch:
    inputs:
      branch_name:
        description: 'The name of the branch to preview.'
        default: 'maintenance-3.1.x'
        required: true
      caller_id:
        description: 'run identifier'
        default: 'maintenance-3.1.x'
        type: string
        required: false

env:
  REGISTRY: docker-internal.packages.nuxeo.com
  REPOSITORY: nuxeo/nuxeo-web-ui

jobs:
  id:
    name: Remote Caller ID ${{ github.event.inputs.caller_id }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - run: echo run identifier ${{ github.event.inputs.caller_id }}

  preview:
    needs: id
    name: Setup
    outputs:
      image: ${{ steps.preview.outputs.image }}
    if: >
      (github.event.action == 'labeled' && github.event.label.name == 'preview') ||
      contains(github.event.pull_request.labels.*.name, 'preview') ||
      github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          registry-url: 'https://packages.nuxeo.com/repository/npm-public/'
          scope: '@nuxeo'

      - name: Set branch name
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            RAW_BRANCH="${GITHUB_HEAD_REF}"
          else
            RAW_BRANCH="${{ github.event.inputs.branch_name }}"
          fi
          echo "BRANCH_NAME=$RAW_BRANCH" >> $GITHUB_ENV
          echo "BRANCH_NAME_SANITIZED=$(echo $RAW_BRANCH | sed 's/[^[:alnum:]-]/-/g' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Determine nuxeo-web-ui branch to use
        uses: nuxeo/ui-team-gh-actions/get-branch@ca09d5c52a62e297502d3572c36d813be927982a
        id: pick_nuxeo_web_ui_branch
        with:
          repository: nuxeo/nuxeo-web-ui
          branch: ${{ env.BRANCH_NAME }}
          default-branch: maintenance-3.1.x

      - uses: actions/checkout@v6
        with:
          ref: ${{ steps.pick_nuxeo_web_ui_branch.outputs.branch }}

      - name: Prepare environment
        run: |
          echo "VERSION=$(npx -c 'echo "$npm_package_version"')-$BRANCH_NAME_SANITIZED" >> $GITHUB_ENV

      - name: Determine nuxeo-elements branch to use
        id: pick_nuxeo_elements_branch
        uses: nuxeo/ui-team-gh-actions/get-branch@ca09d5c52a62e297502d3572c36d813be927982a
        with:
          repository: nuxeo/nuxeo-elements
          branch: ${{ env.BRANCH_NAME }}
          default-branch: maintenance-3.1.x

      - name: Checkout the nuxeo-elements repo
        uses: actions/checkout@v6
        with:
          repository: nuxeo/nuxeo-elements
          path: nuxeo-elements
          fetch-depth: 1
          ref: ${{ steps.pick_nuxeo_elements_branch.outputs.branch }}

      - name: Install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PACKAGES_TOKEN }}
        run: |
          npm ci --ignore-scripts
          npm install ./nuxeo-elements/core
          npm install ./nuxeo-elements/ui
          npm install ./nuxeo-elements/dataviz

      - name: Webpack build
        run: npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to Docker registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.NUXEO_DOCKER_USERNAME }}
          password: ${{ secrets.NUXEO_DOCKER_TOKEN }}

      - name: Build and push server image
        uses: docker/build-push-action@v7
        with:
          context: server
          pull: true
          push: true
          file: server/Dockerfile
          tags: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/server:${{ env.VERSION }}

      - name: Build and push image
        uses: docker/build-push-action@v7
        with:
          context: .
          pull: true
          push: true
          file: Dockerfile
          tags: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.VERSION }}
          build-args: SERVER_IMAGE=${{ env.REGISTRY }}/${{ env.REPOSITORY }}/server:${{ env.VERSION }}

      - name: Set preview image reference
        id: preview
        run: |
          echo "image=${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.VERSION }}" >> $GITHUB_OUTPUT
          echo "PREVIEW_IMAGE=${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.VERSION }}" >> $GITHUB_ENV

      - uses: actions/github-script@v9.0.0
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `:star: PR preview image published: \`${process.env.PREVIEW_IMAGE}\``
            })

  result:
    name: "Result: ${{ needs.preview.outputs.image }}"
    needs: preview
    runs-on: ubuntu-latest
    permissions:
      contents: read
    if: github.event_name == 'workflow_dispatch'
    steps:
      - run: echo ${{ needs.preview.outputs.image }}