name: Provision preview environment

on:
  workflow_call:
    inputs:
      branch_name:
        description: 'The branch to provision a preview'
        default: 'maintenance-3.0.x'
        required: true
        type: string
    outputs:
      url:
        description: 'The preview url'
        value: ${{ jobs.preview.outputs.url }}

env:
  DOCKER_REGISTRY: us-east1-docker.pkg.dev
  DOCKER_IMAGE: ${{ secrets.GKE_PROJECT }}/webui/nuxeo-web-ui
  GKE_CLUSTER: jx-prod
  GKE_ZONE: us-east1-b

jobs:
  preview:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.preview.outputs.url }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 10
        registry-url: 'https://packages.nuxeo.com/repository/npm-public/'
        scope: '@nuxeo'

    - name: Prepare environment
      run: |
        BRANCH_NAME=${{ inputs.branch_name }}
        echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
        echo "VERSION=$(npx -c 'echo "$npm_package_version"')-$BRANCH_NAME" >> $GITHUB_ENV
        echo "PREVIEW_NAMESPACE=nuxeo-web-ui-$(echo $BRANCH_NAME | sed 's/[^[:alnum:]-]/-/g' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    # TODO - replace this with get-branch
    - name: Determine nuxeo-elements branch to use
      id: pick_nuxeo_elements_branch
      run: |
        if git ls-remote --exit-code --heads https://github.com/nuxeo/nuxeo-elements ${{ inputs.branch_name }}; then
          echo ::set-output name=branch::${{ inputs.branch_name }}
        else
          echo ::set-output name=branch::maintenance-3.0.x
        fi

    - name: Checkout the nuxeo-elements repo
      uses: actions/checkout@v2
      with:
        repository: nuxeo/nuxeo-elements
        path: nuxeo-elements
        fetch-depth: 1
        ref: ${{ steps.pick_nuxeo_elements_branch.outputs.branch }}

    - name: Install
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        npm install nuxeo-elements/core
        npm install nuxeo-elements/ui
        npm install nuxeo-elements/dataviz
        npm install

    - name: Webpack build
      run: |
        npm run build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: _json_key
        password: ${{ secrets.GKE_SA_KEY }}

    - name: Build and push server image
      uses: docker/build-push-action@v2
      with:
        context: server
        pull: true
        push: true
        file: server/Dockerfile
        tags: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}/server:${{ env.VERSION }}

    - name: Build and push image
      uses: docker/build-push-action@v2
      with:
        context: .
        pull: true
        push: true
        file: Dockerfile
        tags: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}:${{ env.VERSION }}
        build-args: SERVER_IMAGE=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}/server:${{ env.VERSION }}

    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v0.2.1
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        project_id: ${{ secrets.GKE_PROJECT }}
        credentials: ${{ secrets.GKE_SA_KEY }}

    - name: Check preview namespace
      id: preview_ns
      run: |
        echo ::set-output name=exists::$(kubectl get namespace ${PREVIEW_NAMESPACE})

    - name: Create preview namespace
      if: ${{ !steps.preview_ns.outputs.exists }}
      run: |
        kubectl create namespace ${PREVIEW_NAMESPACE}

    - name: Install preview
      id: preview
      working-directory: ./charts/preview
      run: |
        # add helm jx repo
        helm repo add jx https://jenkins-x-charts.github.io/v2/

        # substitute env variables in values.yaml
        mv values.yaml values.yaml.tosubst
        envsubst < values.yaml.tosubst > values.yaml

        # update helm deps
        helm dependency update .

        # install
        helm upgrade --install --namespace ${PREVIEW_NAMESPACE} ${PREVIEW_NAMESPACE} .

        # ensure the deployment is restarted to pull the new preview image
        kubectl rollout restart deployment ${PREVIEW_NAMESPACE}-preview --namespace ${PREVIEW_NAMESPACE}
        
        echo "PREVIEW_URL=https://preview-${PREVIEW_NAMESPACE}.webui.dev.nuxeo.com" >> $GITHUB_ENV

        echo ::set-output name=url::"https://preview-${PREVIEW_NAMESPACE}.webui.dev.nuxeo.com"
