name: Remote Cleanup

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'The name of the branch to preview.'
        default: 'maintenance-3.0.x'
        required: true
      caller_id:
        description: 'run identifier'
        default: 'maintenance-3.0.x'
        type: string
        required: false

env:
  GKE_CLUSTER: jx-prod
  GKE_ZONE: us-east1-b
  REFERENCE_BRANCH: maintenance-3.0.x

jobs:
  id:
    name: Remote Caller ID ${{ github.event.inputs.caller_id }}
    runs-on: ubuntu-latest
    steps:
      - name: ${{ github.event.inputs.id }}
        run: echo run identifier ${{ github.event.inputs.id }}
  cleanup:
    needs: id
    name: Preview
    runs-on: ubuntu-latest
    steps:

    - name: Determine nuxeo-web-ui branch to use
      uses: nuxeo/ui-team-gh-actions/get-branch@ca09d5c52a62e297502d3572c36d813be927982a
      id: pick_nuxeo_web_ui_branch
      with:
        repository: nuxeo/nuxeo-web-ui
        branch: ${{ github.event.inputs.branch_name }}
        default-branch: ${{ env.REFERENCE_BRANCH }}

    - name: Prepare environment
      run: |
        BRANCH_NAME=${{ steps.pick_nuxeo_web_ui_branch.outputs.branch }}
        echo "PREVIEW_NAMESPACE=nuxeo-web-ui-$(echo $BRANCH_NAME | sed 's/[^[:alnum:]-]/-/g' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v0.2.1
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        project_id: ${{ secrets.GKE_PROJECT }}
        credentials: ${{ secrets.GKE_SA_KEY }}

    - name: Cleanup preview namespace
      continue-on-error: true
      run: |
        kubectl delete ns ${PREVIEW_NAMESPACE}
