name: Test

on:
  pull_request:
    branches:
      - maintenance-3.1.x
      - lts-2025

  workflow_call:
    inputs:
      branch:
        description: 'Branch to test'
        type: string
        required: false
    secrets:
      NPM_PACKAGES_TOKEN:
        required: true
      SAUCE_ACCESS_KEY:
        required: false

permissions:
  contents: read

env:
  BRANCH_NAME: ${{ github.head_ref || inputs.branch || github.ref_name }}

jobs:
  unit-test:
    runs-on:
      group: medium-4cpu-runners

    steps:
      - uses: catchpoint/workflow-telemetry-action@v2
        with:
          comment_on_pr: false

      - uses: actions/checkout@v6
        with:
          ref: ${{ env.BRANCH_NAME }}

      - uses: actions/setup-node@v6
        with:
          registry-url: 'https://packages.nuxeo.com/repository/npm-public/'
          scope: '@nuxeo'
          node-version: 22

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PACKAGES_TOKEN }}
        run: npm install

      - name: Unit tests
        # Disabling SauceLabs. Karma is not compatible with SauceLabs v4
        # env:
        #   SAUCE_USERNAME: nuxeo-web-ui
        #   SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        run: npm run test