name: Test

on:
  pull_request:
    branches:
      - maintenance-3.1.x
  workflow_call:
    inputs:
      branch:
        description: 'The current branch'
        default: maintenance-3.1.x
        type: string
        required: false
    secrets:
      NPM_PACKAGES_TOKEN:
        description: 'NPM_PACKAGES_TOKEN'
        required: true
      SAUCE_ACCESS_KEY:
        description: 'SAUCE_ACCESS_KEY'
        required: true

env:
  BRANCH_NAME: ${{ github.head_ref || inputs.branch || 'maintenance-3.1.x' }}

jobs:
  unit-test:
    runs-on: [ self-hosted, master ]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH_NAME }}

      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://packages.nuxeo.com/repository/npm-public/'
          scope: '@nuxeo'
          node-version: 22

      - name: Install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm cache clean --force
          npm install

      - name: Check tools
        run: |
          which curl || echo "curl not found"
          which tar || echo "tar not found"
          which bzip2 || echo "bzip2 not found"
          uname -a

      - name: Install Firefox manually
        run: |
          echo "Downloading Firefox..."
          curl -L "https://download.mozilla.org/?product=firefox-latest&os=linux64&lang=en-US" -o firefox.tar.bz2
          tar xjf firefox.tar.bz2
          mv firefox "$HOME/firefox"
          echo "FIREFOX_BIN=$HOME/firefox/firefox" >> $GITHUB_ENV

      - name: Unit tests
        # Disabling SauceLabs. Karma is not compatible with SauceLabs v4
        env:
          FIREFOX_BIN: ${{ env.FIREFOX_BIN }}
        #   SAUCE_USERNAME: nuxeo-web-ui
        #   SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        run: npm run test